### ISSUE TITLE
Multiple LoRA seem not to be working

### ISSUE THREAD

**Issue by gulshansainis** [lucataco/cog-flux-dev-multi-lora#1]
I tried `lucataco/flux-dev-lora` where I was able to load the safetensor from HF and apply LoRA however same LoRA is not working in `lucataco/cog-flux-dev-multi-lora`. 

if required I can share output or other inputs to debug issue

**Comment by lucataco** [comment]
Please share your LoRA or prediction output

**Comment by ghost** [comment]
I am getting this error:

```
Traceback (most recent call last):
  File "/root/cog-flux-dev-multi-lora/flux.py", line 359, in <module>
    main()
  File "/root/cog-flux-dev-multi-lora/flux.py", line 338, in main
    output_paths = predictor.predict(
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/root/cog-flux-dev-multi-lora/flux.py", line 272, in predict
    self.load_loras(hf_loras, lora_scales)
  File "/root/cog-flux-dev-multi-lora/flux.py", line 211, in load_loras
    self.txt2img_pipe.set_adapters(adapter_names, adapter_weights=adapter_weights)
  File "/usr/local/lib/python3.10/dist-packages/diffusers/loaders/lora_base.py", line 573, in set_adapters
    model.set_adapters(adapter_names, _component_adapter_weights[component])
KeyError: 'transformer'
root@7ca5b7142493:~/cog-flux-dev-multi-lora# 
```

**Comment by lucataco** [comment]
appears to be an incompatible LoRA format
