### ISSUE TITLE
some lora (XLabs-AI/flux-RealismLora) will throw exception

### ISSUE THREAD

**Issue by mylovelycodes** [lucataco/cog-flux-dev-multi-lora#4]
Hi,

some lora (eg: XLabs-AI/flux-RealismLora) will throw exception
Please check

## error:

Cannot copy out of meta tensor; no data! Please use torch.nn.Module.to_empty() instead of torch.nn.Module.to() when moving module from meta to a different device.

## env:

https://replicate.com/lucataco/flux-dev-multi-lora

## logs:

Using seed: 21205
Prompt: xxxx.
txt2img mode
Downloading LoRA weights from - Replicate URL: https://replicate.delivery/yhqm/xxxx/trained_model.tar
Loading LoRA took: 0.40 seconds
Downloading LoRA weights from - HF path: XLabs-AI/flux-RealismLora
Loading LoRA took: 0.71 seconds
Traceback (most recent call last):
File "/root/.pyenv/versions/3.11.10/lib/python3.11/site-packages/cog/server/worker.py", line 349, in _predict
result = predict(**payload)
^^^^^^^^^^^^^^^^^^
File "/root/.pyenv/versions/3.11.10/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
return func(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^
File "/src/predict.py", line 308, in predict
pipe = pipe.to("cuda")
^^^^^^^^^^^^^^^
File "/root/.pyenv/versions/3.11.10/lib/python3.11/site-packages/diffusers/pipelines/pipeline_utils.py", line 435, in to
module.to(device, dtype)
File "/root/.pyenv/versions/3.11.10/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1174, in to
return self._apply(convert)
^^^^^^^^^^^^^^^^^^^^
File "/root/.pyenv/versions/3.11.10/lib/python3.11/site-packages/torch/nn/modules/module.py", line 780, in _apply
module._apply(fn)
File "/root/.pyenv/versions/3.11.10/lib/python3.11/site-packages/torch/nn/modules/module.py", line 780, in _apply
module._apply(fn)
File "/root/.pyenv/versions/3.11.10/lib/python3.11/site-packages/torch/nn/modules/module.py", line 780, in _apply
module._apply(fn)
[Previous line repeated 3 more times]
File "/root/.pyenv/versions/3.11.10/lib/python3.11/site-packages/torch/nn/modules/module.py", line 805, in _apply
param_applied = fn(param)
^^^^^^^^^
File "/root/.pyenv/versions/3.11.10/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1167, in convert
raise NotImplementedError(
NotImplementedError: Cannot copy out of meta tensor; no data! Please use torch.nn.Module.to_empty() instead of torch.nn.Module.to() when moving module from meta to a different device.

**Comment by lucataco** [comment]
Xlabs-AI trained their LoRAs differently, try using their [Comfy Converted LoRAs](https://huggingface.co/XLabs-AI/flux-lora-collection/tree/main)
